version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    restart: always
    volumes:
      - './postgres:/var/lib/postgresql/data'
    ports:
      - '6432:5432'  

  app:
    depends_on:
      - 'postgres'
    build: .
    command: bash start
    ports:
      - '3000:3000'
    volumes:
      - '.:/araguaia'        